### PR TITLE
Description of JSONP format extended (Dynamic parameter names)

### PR DESCRIPTION
**Pull request by HolQue**

### CODE REVIEW

**Comment by test-fullautomation** [comment]
Hi @HolQue ,
please resolve the merge conflict.
Thank you,
 Thomas

**Comment by HolQue** [comment]
Hi Thomas,

I am confused and have no idea what is the problem. The merge conflict is caused by the PDF file. To solve the merge conflict I committed a deletion of this file and after this I added the file again. Why is there still a merge conflict?

OK, I will delete the file again. Maybe this solves the merge conflict. After your merge I restore the file.

Long winded.

**Comment by HolQue** [comment]
Hi Thomas,

please decline this pull request. I will commit again based on latest stabi branch.

**Comment by test-fullautomation** [comment]
declined as per wish from Holger.

**Pull request closed without merging**
