### PR TITLE
Refactor code comment format base on genpackagedocs feature

### PR DESCRIPTION
**Pull request by namsonx**

### CODE REVIEW

**Comment by test-fullautomation** [comment]
Hi Son,
thank you for your updated and improved documentation.
Still there is much to do. Please contact Holger how to make it smart.
E.g.:
Chapter 3.2 is very bad formatted, introduction is missing... Please check the generaded PDF.
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi Son,
I wanted to link the pdf documentation now for the release mail.
Unfortunately the most important parts chapter 1 introduction and 2 description are still missing.
Please provide this with this pullrequest, too.
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas,

     I have just updated the Introduction.rst and Description.rst files. The new RobotFramework_Testsuites.pdf file look like below after I built and generated:
[RobotFramework_Testsuites.pdf](https://github.com/test-fullautomation/robotframework-testsuitesmanagement/files/9908460/RobotFramework_Testsuites.pdf)
     Could you please help me review this new document?

Thank you,
Son

**Review by HolQue — COMMENTED** [review]
Please find my comments in sticky notes in the attached PDF.
[RobotFramework_Testsuites_reviewed_QT.pdf](https://github.com/test-fullautomation/robotframework-testsuitesmanagement/files/9909048/RobotFramework_Testsuites_reviewed_QT.pdf)

**Comment by namsonx** [comment]
Hello Holger,

     Thank you for your comments, I will go through and update the documentation according to your review :)

Thank you,
Son

**Comment by namsonx** [comment]
Hello Holger,

     I have just updated the document according to your review and generated new Testuistes_Management documentation.
     Please help review a new document which is attached in this comment
[RobotFramework_Testsuites.pdf](https://github.com/test-fullautomation/robotframework-testsuitesmanagement/files/9917930/RobotFramework_Testsuites.pdf)

Thank you
Son

**Comment by HolQue** [comment]
Hello Son,

there are some smaller typos left. See sticky notes.
[RobotFramework_Testsuites_reviewed_2_QT.pdf](https://github.com/test-fullautomation/robotframework-testsuitesmanagement/files/9927337/RobotFramework_Testsuites_reviewed_2_QT.pdf)

**Comment by test-fullautomation** [comment]
Hi Son,
please don't be frustrated :-) Goal is to have a nice documentation for our OSS users.
Holger reviews very carefully. Please consider also his text samples and take care that you don't overlook findings.
Thank you,
 Thomas

**Review by test-fullautomation — APPROVED** [review]
Hi Son,

looks much better than before to me!

Thank you,
 Thomas

**Pull request merged**
