### PR TITLE
Update history

### PR DESCRIPTION
**Pull request by namsonx**

### CODE REVIEW

**Review by HolQue — CHANGES_REQUESTED** [review]
Hi Son,

changes made only here have no effect. You need to adapt version and date also in packageversion.py and you need to generate again the PDF documentation.

**Comment by test-fullautomation** [comment]
Hi Son,

Thank you for your pull request.
Can you please update the PDF documentation and packageversion too.

Thank you, 
Thomas

**Comment by namsonx** [comment]
Hello @HolQue, 
Thank you for your comment, I made the mistake.

Hello Thomas,
I have just updated the packageversion too.

Thank you,
Son

**Review by test-fullautomation — APPROVED** [review]
Hi Son,
looks good to me!

Please regenerate the documentation and check it in, too.
This one here is unfortunately old:
https://github.com/test-fullautomation/robotframework-testsuitesmanagement/blob/develop/RobotFramework_TestsuitesManagement/RobotFramework_TestsuitesManagement.pdf

Thank you,
Thomas

**Review by test-fullautomation — CHANGES_REQUESTED** [review]
Hi Son,
please provide this change as soon as possible.
I wait that I can build 0.7.0.7 version.

Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas,

I updated pdf file.

Thank you,
Son

**Review by test-fullautomation — APPROVED** [review]
Hi Son,
very good!
Thank you,
 Thomas

**Pull request merged**
