### PR TITLE
Ntd1hc/bug/reference version number not set properly

### PR DESCRIPTION
**Pull request by ngoan1608**
Hi,

This PR introduces the `package_context.json` which allow this package to work in many contexts.
The function names and documents have also updated accordingly.

- To test the stand-alone context, you can checkout this branch and install this package.
- To test in RobotFramework AIO context, you can get the build AIO packages from my testing (personal) build pipeline https://github.com/ngoan1608/RobotFramework_AIO/actions/runs/5116933073

Please review and give your feeling about this change.
The PR to update build pipelines will be created soon.

Thank you,
Ngoan

### CODE REVIEW

**Review by HolQue — COMMENTED** [review]
Hi Ngoan,

cool! Stand-alone version control works. Error message fine.

Code is much better now!

**Comment by HolQue** [comment]
Hi Ngoan,

I also would like to test in AIO context. Where can I find `package_context.json`?

**Comment by ngoan1608** [comment]
> Hi Ngoan,
> 
> I also would like to test in AIO context. Where can I find `package_context.json`?

Hi Holger,

The `package_context,json` is generated by build pipeline (there is bash script generates that file then copy to this package before executing `setup.py`).

You can get the AIO packages from above testing build pipeline https://github.com/ngoan1608/RobotFramework_AIO/actions/runs/5116933073.
The `package_context,json` for OSS will be installed along with AIO package.

Please let me know in case you cannot access that build (it is my forked repo).

Thank you,
Ngoan

**Comment by HolQue** [comment]
Hi Ngoan,

I am not sure about the access. I cannot find the build artefacts. Maybe you send me a version of this file per email and tell me where to place. I need at least such a file also for the adaption of the self test.

**Comment by ngoan1608** [comment]
Hi Holger,

You can scroll down to the bottom to get the artifact. I put the direct link to download AIO packages below:
- windows-package: https://github.com/ngoan1608/RobotFramework_AIO/suites/13229804665/artifacts/720777098
- linux-package: https://github.com/ngoan1608/RobotFramework_AIO/suites/13229804665/artifacts/720777096
After installation, the `package_context.json` can be found under `$RobotPythonPath/Lib/site-packages/RobotFramework_TestsuitesManagement/Config` folder.

Here is the content of `package_context.json` of above installers (RobotFramework AIO - OSS context):
```
{
		"installer_location" : "https://github.com/test-fullautomation/RobotFramework_AIO/releases",
		"bundle_name"        : "RobotFramework AIO",
		"bundle_version"     : "0.8.0.0",
		"bundle_version_date": "05.2023"
   }
```

Thank you,

**Comment by HolQue** [comment]
Hi Ngoan,

great!

Also with `package_context.json` it works: version control fine, error message fine!

**Review by test-fullautomation — CHANGES_REQUESTED** [review]
Hi Ngoan,
very good!
Please solve the merge conflict.
Thank you,
 Thomas

**Comment by ngoan1608** [comment]
Hi Thomas,

Merge conflict has been solved.

Thank you,
Ngoan

**Pull request merged**
