### PR TITLE
Change default json config file of configuration l4 to jsonp

### PR DESCRIPTION
**Pull request by namsonx**

### CODE REVIEW

**Review by test-fullautomation — APPROVED** [review]
Hi Son,
thank you for the quick pull-request.
Unfortunately there is a merge conflict. Please resolve and update.
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas,

I have just resolved the conflict.

Thank you,
Son

**Review by HolQue — COMMENTED** [review]
Fine to me!

**Comment by HolQue** [comment]
CAUTION: renamed jsonp file is not installed. New extension need to be added in

"PACKAGEDATA" : ["*.pdf","./Config/*.json"],

**Review by test-fullautomation — APPROVED** [review]
Hi Son,

looks good to me!

Thank you,
 Thomas

**Pull request merged**
