### PR TITLE
Disable additional properties at the top level of json config file.

### PR DESCRIPTION
**Pull request by namsonx**

### CODE REVIEW

**Review by HolQue — CHANGES_REQUESTED** [review]
Hi Son,

unfortunately this does not work. Please try the following use case:

* Parameter configuration file imports another configuration file.
* The imported configuration file initializes a parameter (teststring_bench).
* Within a local configuration file this parameter is updated.

Outcome:

`[ ERROR ] Verification against JSON schema failed: 'Additional properties are not allowed ("str(${params}['global']['teststring_bench'])" was unexpected)'`

And also this error message contains the type cast `str`.

**Comment by namsonx** [comment]
Hi Holger,

As we discussed before, I changed "additionalProperties" from true to false, it means the additional parameters are not allow at the top level of configuration file excepted "Maximum_version" and "Minimum_version". Because the number of parameters at the top level of configuration file will be put into ${CONFIG} object and these parameters are fixed.

in your case, the parameter "teststring_bench" have to place in params['global'].

For the error message contains the type cast str, I will update it.

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

this cannot be the solution!

The parameter is initialized within an imported file (and later shall be overwritten by a local config). The reason for the initialization within an imported file is to avoid redundancies in variant specific configuration files - because it's a parameter that shall have the same value for all variants. We never have discussed that this shall not be possible any more.

I guess that you apply the same JSON schema file to both the parameter configuration file and imported files. But it's obvious that this cannot work, because these files are different. You can check for additional parameters in parameter configuration files, but not immediately in imported files. The [import] statement is placed within params/global. Therefore also the imported values have the proper scope and should therefore not violate the "no additional parameter at top level" rule.

**Comment by namsonx** [comment]
Hello Holger,

I do the JSON schema check after I use jsonpreprocessor to handle all json configuration files as well as local configuration file.
Can you give me your json config files? it will help me understand clearly your scenario.]

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

please refer to

https://github.com/test-fullautomation/robotframework-tutorial/blob/develop/900_building_testsuites/doc_src/exercise-06.robot.rst

**Comment by namsonx** [comment]
Hello Holger,

You are right! It my mistake cause I forgot checking and removing nested parameters in local config object before updating localconfig to robot config object then do JSON schema check.
I had added new commit to this pull-request to solve the problem. Could you please help me check again.

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

thats's it. Works fine now!

**Review by test-fullautomation — APPROVED** [review]
Hi Son,
looks good to me!
Thank you,
 Thomas

**Pull request merged**
