### PR TITLE
Remove warning log output in case robot run with configuration level 1

### PR DESCRIPTION
**Pull request by namsonx**

### CODE REVIEW

**Review by HolQue — CHANGES_REQUESTED** [review]
Hi Son,
level 1 should not cause a warning any more, that's OK. But level 4 should cause a warning (like implemented before). Because level 4 should not happen. It's only an unwanted fallback solution. This is worth a warning.

**Comment by namsonx** [comment]
> Hi Son, level 1 should not cause a warning any more, that's OK. But level 4 should cause a warning (like implemented before). Because level 4 should not happen. It's only an unwanted fallback solution. This is worth a warning.

Hi Holger,
I have just changed back the log output of configuration level 4 to warninng.

**Comment by HolQue** [comment]
Fine to me now!

**Review by test-fullautomation — APPROVED** [review]
Hi Son,
looks good to me!
Thank you,
 Thomas

**Pull request merged**
