### PR TITLE
Update checking duplicated config files in configuration level3

### PR DESCRIPTION
**Pull request by namsonx**

### CODE REVIEW

**Review by HolQue — COMMENTED** [review]
Hi Son,

unfortunately merge conflict with https://github.com/test-fullautomation/robotframework-testsuitesmanagement/pull/179

Reason: In docstrings of CConfig.py I have renamed the JSON file extensions from `.json` to `.jsonp` and I created a new PDF. Could you please take over these changes in your pull request also? Are only few positions.

**Comment by namsonx** [comment]
> Hi Son,
> 
> unfortunately merge conflict with #179
> 
> Reason: In docstrings of CConfig.py I have renamed the JSON file extensions from `.json` to `.jsonp` and I created a new PDF. Could you please take over these changes in your pull request also? Are only few positions.

Hello Holger,

Your pull-request could be merged first then I will resolve conflicts of my pull-request :)

Thank you,
Son

**Review by test-fullautomation — CHANGES_REQUESTED** [review]
Hi Son,
please solve the merge conflict.
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hi Thomas,

The conflict is merged.

Thank you,
Son

**Pull request merged**
